[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube = "0.6.0"
tokio = { version = "1", features = ["full", "rt-multi-thread"] }
url = "2.4.0"
youtube_dl = "0.9.0"
