[package]
name = "stickeries"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
teloxide = "0.13.0"
tempfile = "3.17.1"
tokio = { version = "1.43.0", features = ["full"] }
